apiVersion: v1
kind: Service
metadata:
  name: dashboard-anpr
  labels:
    app: dashboard-anpr
spec:
  ports:
  - port: 5000
  selector:
    app: dashboard-anpr
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dashboard-anpr-deployment
spec:
  replicas: 1
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: dashboard-anpr
    spec:
      containers:
      - name: dashboard-anpr
        image: nexus.daf.teamdigitale.it/dashboard-anpr:1.0.0
        imagePullPolicy: Always
        ports:
        - name: client
          containerPort: 5000
        securityContext:
          privileged: true
          runAsUser: 0